//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskBoardWebClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskBoardWebClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ID&quot;:1,&quot;AssignedToDisplay&quot;:&quot;&quot;,&quot;RemainingTime&quot;:&quot;&quot;,&quot;Project&quot;:&quot;projectX&quot;,&quot;X&quot;:&quot;5px&quot;,&quot;Y&quot;:&quot;90px&quot;,&quot;Transform&quot;:&quot;transformed-right&quot;,&quot;EditURL&quot;:&quot;http://bing.com&quot;,&quot;State&quot;:&quot;Active&quot;,&quot;RemainingHoursHistory&quot;:[],&quot;OriginalEstimate&quot;:&quot;&quot;,&quot;Title&quot;:&quot;Build Taskboard &quot;,&quot;AssignedTo&quot;:&quot;Franco&quot;},{&quot;ID&quot;:2,&quot;AssignedToDisplay&quot;:&quot;&quot;,&quot;RemainingTime&quot;:&quot;&quot;,&quot;Project&quot;:&quot;projectX&quot;,&quot;X&quot;:&quot;5px&quot;,&quot;Y&quot;:&quot;90px&quot;,&quot;Transform&quot;:&quot;transformed-right&quot;,&quot;EditURL&quot;:&quot;http://bing.com&quot;,&quot;State&quot;:&quot;Active&quot;,&quot;RemainingHoursHistory&quot;:[],&quot;OriginalEstimate&quot;:&quot;&quot;,&quot;Title&quot;:&quot;Take a break&quot;,&quot;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lanes {
            get {
                return ResourceManager.GetString("lanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ID&quot;:1,&quot;AssignedToDisplay&quot;:&quot;&quot;,&quot;RemainingTime&quot;:&quot;&quot;,&quot;Project&quot;:&quot;projectX&quot;,&quot;X&quot;:&quot;5px&quot;,&quot;Y&quot;:&quot;90px&quot;,&quot;Transform&quot;:&quot;transformed-right&quot;,&quot;EditURL&quot;:&quot;http://bing.com&quot;,&quot;State&quot;:&quot;Active&quot;,&quot;RemainingHoursHistory&quot;:[],&quot;OriginalEstimate&quot;:&quot;&quot;,&quot;Title&quot;:&quot;Build Taskboard &quot;,&quot;AssignedTo&quot;:&quot;Franco&quot;},{&quot;ID&quot;:2,&quot;AssignedToDisplay&quot;:&quot;&quot;,&quot;RemainingTime&quot;:&quot;&quot;,&quot;Project&quot;:&quot;projectX&quot;,&quot;X&quot;:&quot;5px&quot;,&quot;Y&quot;:&quot;90px&quot;,&quot;Transform&quot;:&quot;transformed-right&quot;,&quot;EditURL&quot;:&quot;http://bing.com&quot;,&quot;State&quot;:&quot;Active&quot;,&quot;RemainingHoursHistory&quot;:[],&quot;OriginalEstimate&quot;:&quot;&quot;,&quot;Title&quot;:&quot;Take a break&quot;,&quot;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
    }
}
